version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: skooly-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-skooly_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-skooly_password}
      POSTGRES_DB: ${DB_NAME:-skooly_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: skooly-cache
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: skooly-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-skooly_storage_user}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-skooly_storage_password}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
